from configs import paths as cfg

# small wrapper to expose configured paths
RAW_AUDIO_DIR = cfg.RAW_AUDIO_DIR
PROCESSED_AUDIO_DIR = cfg.PROCESSED_AUDIO_DIR
STORAGE_TRANSCRIPTS = cfg.STORAGE_TRANSCRIPTS
STORAGE_EMBEDDINGS = cfg.STORAGE_EMBEDDINGS
STORAGE_CHUNKS = cfg.STORAGE_CHUNKS
MODELS_DIR = cfg.MODELS_DIR
FIGURES_DIR = cfg.FIGURES_DIR
OUTPUTS_DIR = cfg.OUTPUTS_DIR
